djangoproject/djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from posts import views

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),



]

djangoproject/posts/urls.py
from django.conf.urls import url
from django.urls import path,include
from . import views

app_name= 'posts'

urlpatterns = [
	path('', views.index,name='index'),
	path('News/', views.news, name="News"),
	path('stock/', views.stockprice, name="stockprice")

]

djangoproject/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class News(models.Model):
    Id = models.IntegerField(primary_key=True)
    StockNews = models.TextField(blank=True)

    def __str__(self):
        return self.StockNews


class Stock(models.Model):
    StockName = models.CharField(blank=True, max_length=100)
    CurrentPrice = models.FloatField(null=True,blank=True)

    def __str__(self):
        return self.StockName

djangoproject/posts/views.py
from django.shortcuts import render,redirect

from .models import *
from django.http import HttpResponse
# Create your views here.
def index(request):
	return render(request, 'posts/fullpage.html')

def news(request):
    news_list=News.objects.all()
    NewsDic={'news':news_list}
    return render(request,'posts/News.html',context=NewsDic)


def stockprice(request):
    stock_list=Stock.objects.all()
    StockDic={'stocks':stock_list}
    return render(request,'posts/stock.html',context=StockDic)

djangoproject/posts/templates/posts/News.html
  <!doctype html>
<html lang="en">

<!-- Mirrored from simpleqode.bitbucket.io/incline/fullpage.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 10 Jan 2019 17:16:26 GMT -->
<head>
  {% load staticfiles %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Favicons -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'posts/ico/apple-touch-icon.png'%}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'posts/ico/favicon-32x32.png'%}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'posts/ico/favicon-16x16.png'%}">
    <link rel="manifest" href="{%static 'posts/ico/site.webmanifest'%}">
    <link rel="mask-icon" href="{%static 'posts/ico/safari-pinned-tab.svg'%}" color="#5bbad5">
    <link rel="shortcut icon" href="{%static 'posts/ico/favicon.ico'%}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-config" content="{% static 'posts/ico/browserconfig.xml'%}">
    <meta name="theme-color" content="#ffffff">


    <!-- Plugins CSS -->
    <link rel="stylesheet" href="{% static 'posts/libs/flickity/dist/flickity.min.css' %}">
    <link rel="stylesheet" href="{% static 'posts/libs/fullpage.js/dist/fullpage.min.css' %}">
    <link rel="stylesheet" href="{% static 'posts/libs/highlightjs/styles/codepen-embed.css' %}">
    <link rel="stylesheet" href="{% static 'posts/libs/%40fortawesome/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'posts/libs/incline-icons/style.min.css'%}">

    <!-- Theme CSS -->
    <link rel="stylesheet" href="{% static 'posts/css/theme.min.css' %}">

    <!-- Theme CSS -->


    <title>ECON CLUB |</title>
  </head>
  <body>

    <!-- NAVBAR
    ================================================= -->
    <nav class="navbar navbar-expand-xl navbar-dark  navbar-togglable  fixed-top">
      <div class="container">

        <!-- Brand -->
        <a class="navbar-brand" href="{% url 'posts:index' %}">
          <svg class="navbar-brand-svg" viewBox="0 0 245 80" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
            <path d="M0 0 L 20 10 L 0 20 Z" class="navbar-brand-svg-i" fill="currentColor"></path>
            <path d="M0 30 L 20 40 L 0 50 Z M20 45 L 0 55 L 20 65 Z M0 60 L 20 70 L 0 80 Z" fill="currentColor"></path>
            <text x="40" y="70" font-family="Arial, sans-serif" font-size="60" font-weight="bold" letter-spacing="-.025em" fill="currentColor">Econ</text>
          </svg>
        </a>

        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="navbarCollapse">

          <!-- Social -->


          <!-- Links -->
          <ul class="navbar-nav ml-auto">
            <li >
              <a class="nav-link toggle" href="{% url 'posts:index' %}" id="navbarWelcome" role="button"  aria-haspopup="true" aria-expanded="false">
                Welcome
              </a>

            </li>
           <li>
                   <a class="nav-link toggle" href="{% url 'posts:News' %}" role="button"  aria-haspopup="true" aria-expanded="false">
                News
              </a></li>
                 <a class="nav-link toggle" href="{% url 'posts:stockprice' %}" role="button"  aria-haspopup="true" aria-expanded="false">
                stock
              </a></li>



            <li class="nav-item-divider">
              <span class="nav-link">
                <span></span>
              </span>
            </li>

          </ul>

        </div> <!-- / .navbar-collapse -->

      </div> <!-- / .container -->
    </nav>
<main>
 <section class="fp-section">
        <div class="section section-top">

<table class="table table-striped table-bordered table-hover table-condensed ">
  <thead class="thead-dark">
    <tr>

      <th scope="col">Id</th>
<th align="right">News</th>
    </tr>
  </thead>
  <tbody>
      {% csrf_token %}
      {% for nw in news %}
      <tr>
         <td>{{ nw.Id }}</td>
        <td align="center">{{ nw.StockNews }}</td>
      </tr>
      {%endfor%}



  </tbody>
</table>

        </div></section></main>


<section class="fp-section fp-auto-height">
        <footer class="section bg-dark">

          <!-- Triangles -->
          <div class="bg-triangle bg-triangle-light bg-triangle-bottom bg-triangle-left"></div>
          <div class="bg-triangle bg-triangle-light bg-triangle-bottom bg-triangle-right"></div>

          <!--Content -->
          <div class="container">
            <div class="row align-self-center">
              <div class="col-md-auto">

                <!-- Brand -->
                <p>
                  <a href="{% url 'posts:index' %}" class="footer-brand text-white">
                    <svg class="footer-brand-svg" viewBox="0 0 235 80" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                      <path d="M0 0 L 20 10 L 0 20 Z" class="text-primary" fill="currentColor"></path>
                      <path d="M0 30 L 20 40 L 0 50 Z M20 45 L 0 55 L 20 65 Z M0 60 L 20 70 L 0 80 Z" fill="currentColor"></path>
                      <text x="40" y="70" font-family="Arial, sans-serif" font-size="60" font-weight="bold" letter-spacing="-.025em" fill="currentColor">econ</text>
                    </svg>
                  </a>
                </p>
                <div class="row align-items-center">
         <div class="col-md">
        
                <!-- Copyright -->
                <p class="text-white text-muted">
                  <small>
                    &copy; Copyright <span class="current-year"></span> econclub. All rights reserved.
                  </small>
                </p>

              </div></div>
  <div class="row align-items-center">              <div class="col-md">
        
            <!-- Social links -->
            <ul class="list-inline list-unstyled text-md-center">
              
              <li class="list-inline-item ml-3">
                <a href="https://www.facebook.com/StratagemTU/?ref=page_internal">
                  <i class="fab fa-facebook"></i>
                </a>
              </li>
              <li class="list-inline-item ml-3">
                <a href="https://www.instagram.com/econclub">
                  <i class="fab fa-instagram"></i>
                </a>
              </li>
            </ul>

          </div></div>
              </div>
              <div class="col-md">
        
                <!-- Links -->
                <ul class="list-unstyled list-inline text-md-right">
             
              <li class="list-inline-item mr-2">
                <p class="text-white">
                  developed by
                </p>
              </li>
              <li class="list-inline-item">
                <a href="https://in.linkedin.com/in/rohit-kumar-b12717169" class="text-white">
                  Rohit Kumar
            
               
              </li>
              
              <li class="list-inline-item">
               <div class="rohit">
  <img src="{% static 'posts/img/r.jpg'%}" alt="avatar" class="rohit">
</div></a>
              </li></ul>
               <ul class="list-unstyled list-inline text-md-right">
               <li class="list-inline-item">
                <a href="https://in.linkedin.com/in/yuvraj-singh-84b3114a" class="text-white">
                 and Yuraj Singh
            
               
              </li>
              <li class="list-inline-item mr-2">
               <div class="rohit">
  <img src="{% static 'posts/img/01.jpg'%}" alt="avatar" class="rohit"></a>
</div>
              </li></ul>
                
                
            </div>

              </div>
            </div> <!-- / .row -->
            <!-- / .row -->
          </div> <!-- / .container -->

        </footer>
      </section>

    </main>

    <!-- JAVASCRIPT
    ================================================== -->
    <!-- Global JS -->
    <script src="{% static 'posts/libs/jquery/dist/jquery.min.js'%}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCnKt8_N4-FKOnhI_pSaDL7g_g-XI1-R9E"></script>

    <!-- Plugins JS -->
    <script src="{% static 'posts/libs/bootstrap/dist/js/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'posts/libs/flickity/dist/flickity.pkgd.min.js'%}"></script>
    <script src="{% static 'posts/libs/jquery-parallax.js/parallax.min.js'%}"></script>
    <script src="{% static 'posts/libs/waypoints/lib/jquery.waypoints.min.js'%}"></script>
    <script src="{% static 'posts/libs/waypoints/lib/shortcuts/inview.min.js'%}"></script>
    <script src="{% static 'posts/libs/fullpage.js/vendors/scrolloverflow.min.js'%}"></script>
    <script src="{% static 'posts/libs/fullpage.js/dist/fullpage.min.js'%}"></script>
    <script src="{% static 'posts/libs/highlightjs/highlight.pack.min.js'%}"></script>

    <!-- Theme JS -->
    <script src="{% static 'posts/js/theme.min.js'%}"></script>

<!-- Mirrored from simpleqode.bitbucket.io/incline/fullpage.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 10 Jan 2019 17:16:26 GMT -->
</html>

djangoproject/posts/templates/posts/stock.html
 <!doctype html>
<html lang="en">

<!-- Mirrored from simpleqode.bitbucket.io/incline/fullpage.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 10 Jan 2019 17:16:26 GMT -->
<head>
  {% load staticfiles %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Favicons -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'posts/ico/apple-touch-icon.png'%}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'posts/ico/favicon-32x32.png'%}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'posts/ico/favicon-16x16.png'%}">
    <link rel="manifest" href="{%static 'posts/ico/site.webmanifest'%}">
    <link rel="mask-icon" href="{%static 'posts/ico/safari-pinned-tab.svg'%}" color="#5bbad5">
    <link rel="shortcut icon" href="{%static 'posts/ico/favicon.ico'%}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-config" content="{% static 'posts/ico/browserconfig.xml'%}">
    <meta name="theme-color" content="#ffffff">


    <!-- Plugins CSS -->
    <link rel="stylesheet" href="{% static 'posts/libs/flickity/dist/flickity.min.css' %}">
    <link rel="stylesheet" href="{% static 'posts/libs/fullpage.js/dist/fullpage.min.css' %}">
    <link rel="stylesheet" href="{% static 'posts/libs/highlightjs/styles/codepen-embed.css' %}">
    <link rel="stylesheet" href="{% static 'posts/libs/%40fortawesome/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'posts/libs/incline-icons/style.min.css'%}">

    <!-- Theme CSS -->
    <link rel="stylesheet" href="{% static 'posts/css/theme.min.css' %}">

    <!-- Theme CSS -->


    <title>ECON CLUB |</title>
  </head>
  <body>

    <!-- NAVBAR
    ================================================= -->
    <nav class="navbar navbar-expand-xl navbar-dark  navbar-togglable  fixed-top">
      <div class="container">

        <!-- Brand -->
        <a class="navbar-brand" href="{% url 'posts:index' %}">
          <svg class="navbar-brand-svg" viewBox="0 0 245 80" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
            <path d="M0 0 L 20 10 L 0 20 Z" class="navbar-brand-svg-i" fill="currentColor"></path>
            <path d="M0 30 L 20 40 L 0 50 Z M20 45 L 0 55 L 20 65 Z M0 60 L 20 70 L 0 80 Z" fill="currentColor"></path>
            <text x="40" y="70" font-family="Arial, sans-serif" font-size="60" font-weight="bold" letter-spacing="-.025em" fill="currentColor">Econ</text>
          </svg>
        </a>

        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="navbarCollapse">

          <!-- Social -->


          <!-- Links -->
          <ul class="navbar-nav ml-auto">
            <li >
              <a class="nav-link toggle" href="{% url 'posts:index' %}" id="navbarWelcome" role="button"  aria-haspopup="true" aria-expanded="false">
                Welcome
              </a>

            </li>
           <li>
                   <a class="nav-link toggle" href="{% url 'posts:News' %}" role="button"  aria-haspopup="true" aria-expanded="false">
                News
              </a></li>
                 <a class="nav-link toggle" href="{% url 'posts:stockprice' %}" role="button"  aria-haspopup="true" aria-expanded="false">
                stock
              </a></li>



            <li class="nav-item-divider">
              <span class="nav-link">
                <span></span>
              </span>
            </li>

          </ul>

        </div> <!-- / .navbar-collapse -->

      </div> <!-- / .container -->
    </nav>

      <!-- HERO -->
      <section class="fp-section border-bottom">
        <div class="section section-top">
<table class="table table-striped table-bordered table-hover table-condensed ">
  <thead>
    <th>Route</th>
    <th align="right">CurrentPrice</th>
  </thead>

        {% for stock in stocks %}
        <tr>
          <td>{{ stock.StockName }}</td>
          <td>{{ stock.CurrentPrice }}</td>
        </tr>
        {%endfor%}

</table>

        </div>
      </section>
<section class="fp-section fp-auto-height">
        <footer class="section bg-dark">

          <!-- Triangles -->
          <div class="bg-triangle bg-triangle-light bg-triangle-bottom bg-triangle-left"></div>
          <div class="bg-triangle bg-triangle-light bg-triangle-bottom bg-triangle-right"></div>

          <!--Content -->
          <div class="container">
            <div class="row align-self-center">
              <div class="col-md-auto">

                <!-- Brand -->
                <p>
                  <a href="{% url 'posts:index' %}" class="footer-brand text-white">
                    <svg class="footer-brand-svg" viewBox="0 0 235 80" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                      <path d="M0 0 L 20 10 L 0 20 Z" class="text-primary" fill="currentColor"></path>
                      <path d="M0 30 L 20 40 L 0 50 Z M20 45 L 0 55 L 20 65 Z M0 60 L 20 70 L 0 80 Z" fill="currentColor"></path>
                      <text x="40" y="70" font-family="Arial, sans-serif" font-size="60" font-weight="bold" letter-spacing="-.025em" fill="currentColor">econ</text>
                    </svg>
                  </a>
                </p>
                <div class="row align-items-center">
         <div class="col-md">
        
                <!-- Copyright -->
                <p class="text-white text-muted">
                  <small>
                    &copy; Copyright <span class="current-year"></span> econclub. All rights reserved.
                  </small>
                </p>

              </div></div>
  <div class="row align-items-center">              <div class="col-md">
        
            <!-- Social links -->
            <ul class="list-inline list-unstyled text-md-center">
              
              <li class="list-inline-item ml-3">
                <a href="https://www.facebook.com/StratagemTU/?ref=page_internal">
                  <i class="fab fa-facebook"></i>
                </a>
              </li>
              <li class="list-inline-item ml-3">
                <a href="https://www.instagram.com/econclub">
                  <i class="fab fa-instagram"></i>
                </a>
              </li>
            </ul>

          </div></div>
              </div>
              <div class="col-md">
        
                <!-- Links -->
                <ul class="list-unstyled list-inline text-md-right">
             
              <li class="list-inline-item mr-2">
                <p class="text-white">
                  developed by
                </p>
              </li>
              <li class="list-inline-item">
                <a href="https://in.linkedin.com/in/rohit-kumar-b12717169" class="text-white">
                  Rohit Kumar
            
               
              </li>
              
              <li class="list-inline-item">
               <div class="rohit">
  <img src="{% static 'posts/img/r.jpg'%}" alt="avatar" class="rohit">
</div></a>
              </li></ul>
               <ul class="list-unstyled list-inline text-md-right">
               <li class="list-inline-item">
                <a href="https://in.linkedin.com/in/yuvraj-singh-84b3114a" class="text-white">
                 and Yuraj Singh
            
               
              </li>
              <li class="list-inline-item mr-2">
               <div class="rohit">
  <img src="{% static 'posts/img/01.jpg'%}" alt="avatar" class="rohit"></a>
</div>
              </li></ul>
                
                
            </div>

              </div>
            </div> <!-- / .row -->
            <!-- / .row -->
          </div> <!-- / .container -->

        </footer>
      </section>

    </main>

    <!-- JAVASCRIPT
    ================================================== -->
    <!-- Global JS -->
    <script src="{% static 'posts/libs/jquery/dist/jquery.min.js'%}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCnKt8_N4-FKOnhI_pSaDL7g_g-XI1-R9E"></script>

    <!-- Plugins JS -->
    <script src="{% static 'posts/libs/bootstrap/dist/js/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'posts/libs/flickity/dist/flickity.pkgd.min.js'%}"></script>
    <script src="{% static 'posts/libs/jquery-parallax.js/parallax.min.js'%}"></script>
    <script src="{% static 'posts/libs/waypoints/lib/jquery.waypoints.min.js'%}"></script>
    <script src="{% static 'posts/libs/waypoints/lib/shortcuts/inview.min.js'%}"></script>
    <script src="{% static 'posts/libs/fullpage.js/vendors/scrolloverflow.min.js'%}"></script>
    <script src="{% static 'posts/libs/fullpage.js/dist/fullpage.min.js'%}"></script>
    <script src="{% static 'posts/libs/highlightjs/highlight.pack.min.js'%}"></script>

    <!-- Theme JS -->
    <script src="{% static 'posts/js/theme.min.js'%}"></script>

<!-- Mirrored from simpleqode.bitbucket.io/incline/fullpage.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 10 Jan 2019 17:16:26 GMT -->
</html>